import turtle

turtle.speed(10)

turtle.begin_fill()
turtle.forward(50)
turtle.left(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(8)
turtle.left(90)
turtle.forward(4)
turtle.right(90)
turtle.forward(2)
turtle.left(90)
turtle.forward(4)
turtle.left(90)
turtle.forward(2)
turtle.right(90)
turtle.forward(4)
turtle.left(90)
turtle.forward(8)
turtle.end_fill()

turtle.right(90)
turtle.penup()
turtle.forward(88)
turtle.pendown()
turtle.right(90)

turtle.begin_fill()
turtle.forward(8)
turtle.right(90)
turtle.forward(4)
turtle.left(90)
turtle.forward(2)
turtle.right(90)
turtle.forward(4)
turtle.right(90)
turtle.forward(2)
turtle.left(90)
turtle.forward(4)
turtle.right(90)
turtle.forward(8)
turtle.end_fill()

turtle.left(90)
turtle.penup()
turtle.forward(38)
turtle.pendown()
turtle.right(90)
turtle.forward(20)
turtle.right(90)

turtle.forward(50)
turtle.left(180)
turtle.forward(100)

turtle.right(90)
turtle.forward(50)
turtle.left(135)

turtle.begin_fill()
turtle.circle(35,90)
turtle.end_fill()

turtle.penup()
turtle.left(135)
turtle.forward(50)
turtle.right(90)
turtle.pendown()

turtle.forward(150)
turtle.right(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(100)
turtle.begin_fill()
turtle.left(60)
turtle.forward(30)
turtle.right(150)
turtle.forward(50)
turtle.right(150)
turtle.forward(30)
turtle.left(60)
turtle.end_fill()

turtle.penup()
turtle.forward(100)
turtle.pendown()

turtle.left(30)
turtle.forward(58)

turtle.penup()
turtle.right(31)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(2)
turtle.pendown()

turtle.forward(20)
turtle.right(70)
turtle.forward(50)
turtle.left(180)
turtle.forward(100)
turtle.right(180)
turtle.forward(50)
turtle.left(150)
turtle.forward(50)
turtle.right(180)
turtle.forward(100)
turtle.right(180)
turtle.forward(50)

turtle.mainloop()
